"""initialize the models

Revision ID: 4daa9e3c0a85
Revises: 
Create Date: 2026-08-24 22:57:40.149271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4daa9e3c0a85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.Column('reading_level', sa.String(length=2), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('estimated_reading_time', sa.Integer(), nullable=False),
    sa.Column('quiz', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("reading_level IN ('A1', 'A2', 'B1', 'B2')", name='check_reading_level'),
    sa.CheckConstraint('estimated_reading_time > 0', name='check_estimated_reading_time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('current_level', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_level IN ('A1', 'A2', 'B1', 'B2')", name='check_current_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vocabularies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=2), nullable=False),
    sa.CheckConstraint("selected_answer IN ('a', 'b', 'c', 'd')", name='check_assessment_answer_option'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question')
    )
    op.create_table('assessment_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'completed' AND score IS NOT NULL)\n            OR\n            (status = 'skipped' AND score IS NULL)\n            ", name='check_assessment_result_score'),
    sa.CheckConstraint("\n            (status = 'skipped' AND level = 'A1')\n            OR\n            (status = 'completed' AND level IN ('A1', 'A2', 'B1', 'B2'))\n            ", name='check_assessment_result_level'),
    sa.CheckConstraint("level IN ('A1', 'A2', 'B1', 'B2')", name='check_assessment_level'),
    sa.CheckConstraint("status IN ('completed', 'skipped')", name='check_assessment_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    op.create_table('assessment_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'assessment_id')
    )
    op.create_table('global_ai_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('vocabulary', 'sentence', 'passage')", name='check_type'),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_id', 'start_position', 'end_position', 'type', name='uq_reading_selected_text_type')
    )
    op.create_table('reading_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('spaced_repetition', 'fully_completed')", name='check_reading_result_status'),
    sa.CheckConstraint('highest_score >= 0 AND highest_score <= 5', name='check_reading_highest_score'),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reading_id', name='uq_user_reading_result')
    )
    op.create_table('reading_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reading_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'reading_id')
    )
    op.create_table('vocabulary_learning_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('bangla_meaning', sa.Text(), nullable=False),
    sa.Column('example_context', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('reading', 'speaking', 'ielts', 'writing', 'manual')", name='check_vocabulary_content_source_type'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_learning_contents_source', 'vocabulary_learning_contents', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_vocabulary_learning_contents_vocabulary_id', 'vocabulary_learning_contents', ['vocabulary_id'], unique=False)
    op.create_table('reading_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('selected_answer', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_reading_session_question')
    )
    op.create_table('user_vocabularies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_content_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'mastered')", name='check_user_vocabulary_status'),
    sa.CheckConstraint('stage >= 1 AND stage <= 8', name='check_user_vocabulary_stage'),
    sa.ForeignKeyConstraint(['learning_content_id'], ['vocabulary_learning_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_content_id', name='uq_user_learning_content')
    )
    op.create_index('ix_user_vocabularies_due', 'user_vocabularies', ['user_id', 'status', 'next_review_at'], unique=False)
    op.create_table('vocabulary_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage_before', sa.Integer(), nullable=False),
    sa.Column('stage_after', sa.Integer(), nullable=False),
    sa.CheckConstraint("action IN ('MASTER', 'NOT_MASTER')", name='check_vocabulary_review_action'),
    sa.CheckConstraint('stage_after >= 1 AND stage_after <= 8', name='check_review_stage_after'),
    sa.CheckConstraint('stage_before >= 1 AND stage_before <= 8', name='check_review_stage_before'),
    sa.ForeignKeyConstraint(['user_vocabulary_id'], ['user_vocabularies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_reviews_reviewed_at', 'vocabulary_reviews', ['reviewed_at'], unique=False)
    op.create_index('ix_vocabulary_reviews_user_vocabulary_id', 'vocabulary_reviews', ['user_vocabulary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocabulary_reviews_user_vocabulary_id', table_name='vocabulary_reviews')
    op.drop_index('ix_vocabulary_reviews_reviewed_at', table_name='vocabulary_reviews')
    op.drop_table('vocabulary_reviews')
    op.drop_index('ix_user_vocabularies_due', table_name='user_vocabularies')
    op.drop_table('user_vocabularies')
    op.drop_table('reading_answers')
    op.drop_index('ix_vocabulary_learning_contents_vocabulary_id', table_name='vocabulary_learning_contents')
    op.drop_index('ix_vocabulary_learning_contents_source', table_name='vocabulary_learning_contents')
    op.drop_table('vocabulary_learning_contents')
    op.drop_table('user_reading_completions')
    op.drop_table('reading_sessions')
    op.drop_table('reading_results')
    op.drop_table('global_ai_explanations')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_table('assessment_answers')
    op.drop_table('vocabularies')
    op.drop_table('users')
    op.drop_table('readings')
    op.drop_table('assessments')
    # ### end Alembic commands ###
